### ISSUE TITLE
`Invalid URL` reported when shortening Google Photos URL

### ISSUE THREAD

**Issue by ekk88d** [Lemkinator/OneUrl#4]
**Describe the bug**
`Invalid URL` reported when shortening Google Photos URL

**To Reproduce**
1. Create any Google Photos share link, to an album, photo, or video. 
2. The URL outputs as `https://photos.app.goo.gl/***`
3. Switch to OneURL, click `+` sign to shorten new link.
4. Paste long URL and click `Add`

**Expected behavior**
Shortened is.gd URL

**Screenshot**
![iMarkup_20240901_115218](https://github.com/user-attachments/assets/ffd6cb60-0580-466f-8b58-53dbca141d60)

**Smartphone:**
 - Device: Samsung Galaxy S23U
 - OS: Android 14, OneUI 6.1

**Additional context**
I think the app's URL parameters just need to get updated to Google Photos' current format. 

**Separately, but not opening another issue**
OneURL's app icon doesn't show up as an eligible app to Share an URL. Directly sharing an URL, from another app, streamlines the URL shortening process.
Copying a link, then opening OneURL separately, to paste the link, is more cumbersome.

**Comment by Lemkinator** [comment]
Thank you for your detailed issue.

The reason for this issue is that Google Photos links are blacklisted on v.gd/is.gd (they are the same service). Unfortunately, there is nothing I can do to change this, but I will update the error message to inform users of the reason.

If you need to share Google Photos links, you will need to use a different provider. I have tested da.gd and it worked on my side.


In reference to the sharing function:
OneURL should appear as an option when sharing a link. However, on most devices, not all applications are displayed in this list, as the list is determined by the operating system. On your S23, you should be able to locate OneURL by scrolling to the end of the icons, and selecting the "More" option (represented by three dots). Additionally, there should be a pen icon in the top-right corner of this view, which allows you to modify the share panel. This may further enhance your efficiency.


Another way that should also work is if you select text. In that case, OneURL should have an entry in the context menu where you can copy and so on. (This only works when a link is selected, and you also have to click on the three dots in the menu and scroll down.)
